import { PageContainer, ProForm, ProFormSelect, ProFormText, ProTable } from '@ant-design/pro-components'
import { Button, Grid, Space, Tag } from 'antd'
import React, { useCallback, useEffect, useState } from 'react'
import { controlCall, dialCall, getHardwareTopology, listCalls, simulateIncomingCall, type Call, type HardwareTopologyResponse } from '@/api/client'

const operationId=()=>crypto.randomUUID?.()??`call_${Date.now()}_abcdefghijkl`
export default function Calls(){const compact=!Grid.useBreakpoint().md;const [calls,setCalls]=useState<Call[]>([]);const [topology,setTopology]=useState<HardwareTopologyResponse>();const load=useCallback(async()=>{const[c,t]=await Promise.all([listCalls(),getHardwareTopology()]);setCalls(c);setTopology(t)},[]);useEffect(()=>{void load()},[load]);const action=async(id:string,a:'answer'|'reject'|'hangup')=>{await controlCall(id,{action:a});await load()};return <PageContainer title="语音通话" subTitle="拨号、来电模拟和通话控制">
  <ProForm autoFocusFirstInput={false} layout={compact?'vertical':'inline'} onFinish={async v=>{await dialCall({operationId:operationId(),lineId:v.lineId,remoteAddress:v.remoteAddress});await load();return true}} submitter={{searchConfig:{submitText:'拨号'}}}><ProFormSelect name="lineId" label="线路" rules={[{required:true}]} options={(topology?.lines??[]).filter(l=>l.state==='ready'&&l.capabilities.cellularVoice).map(l=>({value:l.id,label:l.displayName}))}/><ProFormText name="remoteAddress" label="号码" rules={[{required:true}]}/></ProForm>
  <ProTable style={{marginTop:16}} search={false} rowKey="id" dataSource={calls} scroll={{x:'max-content'}} toolBarRender={()=>[<Button key="incoming" onClick={async()=>{const line=topology?.lines.find(l=>l.state==='ready'&&l.capabilities.cellularVoice);if(line){await simulateIncomingCall({operationId:operationId(),lineId:line.id,remoteAddress:'+447700900123'});await load()}}}>模拟来电</Button>]} columns={[{title:'时间',dataIndex:'createdAt',valueType:'dateTime'},{title:'线路',dataIndex:'lineId'},{title:'号码',dataIndex:'remoteAddress'},{title:'方向',dataIndex:'direction'},{title:'状态',dataIndex:'state',render:v=><Tag>{String(v)}</Tag>},{title:'控制',render:(_,r)=><Space>{r.state==='incoming'&&<><Button onClick={()=>action(r.id,'answer')}>接听</Button><Button danger onClick={()=>action(r.id,'reject')}>拒接</Button></>}{(r.state==='active'||r.state==='dialing')&&<Button danger onClick={()=>action(r.id,'hangup')}>挂断</Button>}</Space>}]} />
  </PageContainer>}
