import { DeleteOutlined } from '@ant-design/icons'
import { PageContainer, ProForm, ProFormCheckbox, ProFormSelect, ProFormText, ProTable } from '@ant-design/pro-components'
import { Button, Grid, Popconfirm, Space, Tag } from 'antd'
import React, { useCallback, useEffect, useState } from 'react'
import { createNotificationChannel, deleteNotificationChannel, listNotificationChannels, testNotificationChannel, updateNotificationChannel, type NotificationChannel, type NotificationEventKind } from '@/api/client'

const events:NotificationEventKind[]=['sms.received','sms.failed','call.incoming','call.missed','system.degraded']
export default function Notifications(){const compact=!Grid.useBreakpoint().md;const[items,setItems]=useState<NotificationChannel[]>([]);const load=useCallback(async()=>setItems(await listNotificationChannels()),[]);useEffect(()=>{void load()},[load]);return <PageContainer title="通知渠道" subTitle="企业微信与飞书单向出站通知，不接受远程命令">
  <ProForm autoFocusFirstInput={false} layout={compact?'vertical':'inline'} onFinish={async v=>{await createNotificationChannel({provider:v.provider,displayName:v.displayName,webhookUrl:v.webhookUrl,signingSecret:v.signingSecret??'',enabled:true,eventKinds:v.eventKinds});await load();return true}} submitter={{searchConfig:{submitText:'添加渠道'}}}><ProFormSelect name="provider" label="平台" rules={[{required:true}]} options={[{value:'wecom',label:'企业微信'},{value:'feishu',label:'飞书'}]}/><ProFormText name="displayName" label="名称" rules={[{required:true}]}/><ProFormText name="webhookUrl" label="Webhook" width={compact?'md':'xl'} rules={[{required:true,type:'url'}]}/><ProFormText.Password name="signingSecret" label="签名密钥"/><ProFormCheckbox.Group name="eventKinds" label="事件" options={events.map(v=>({value:v,label:v}))} rules={[{required:true}]} /></ProForm>
  <ProTable search={false} rowKey="id" dataSource={items} scroll={{x:'max-content'}} columns={[{title:'名称',dataIndex:'displayName'},{title:'平台',dataIndex:'provider'},{title:'Webhook',dataIndex:'webhookHint'},{title:'事件',dataIndex:'eventKinds',render:v=><Space wrap>{(v as string[]).map(x=><Tag key={x}>{x}</Tag>)}</Space>},{title:'最近投递',dataIndex:'lastDeliveryStatus'},{title:'状态',dataIndex:'enabled',render:v=><Tag color={v?'green':'default'}>{v?'启用':'停用'}</Tag>},{title:'操作',render:(_,r)=><Space><Button onClick={async()=>{await testNotificationChannel(r.id);await load()}}>测试</Button><Button onClick={async()=>{await updateNotificationChannel(r.id,{provider:r.provider,displayName:r.displayName,webhookUrl:'',signingSecret:'',enabled:!r.enabled,eventKinds:r.eventKinds});await load()}}>{r.enabled?'停用':'启用'}</Button><Popconfirm title="删除渠道？" onConfirm={async()=>{await deleteNotificationChannel(r.id);await load()}}><Button danger icon={<DeleteOutlined/>}/></Popconfirm></Space>}]} />
  </PageContainer>}
